# Generated by Django 5.1.2 on 2024-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=30)),
                ('Estrellas', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('numero', models.CharField(max_length=5)),
                ('codigo_hab', models.IntegerField()),
            ],
        ),
    ]
