# Generated by Django 5.1.2 on 2024-11-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ubucacion', models.CharField(max_length=50)),
                ('calif', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estrellas', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='numero',
            new_name='numero_hab',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='Estrellas',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='codigo_hab',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='nombre_hotel',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='piso',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='prec_noch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Reserv_Hotel.hotel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fech_entrada', models.DateField()),
                ('fech_salida', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserv_Hotel.habitacion')),
            ],
        ),
    ]
