# Generated by Django 5.1.2 on 2024-11-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0002_hotel_servicio_rename_numero_habitacion_numero_hab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
