# Generated by Django 5.1.2 on 2024-11-08 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0003_reserva_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fech_entrada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fech_salida',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
