# Generated by Django 5.1.2 on 2024-11-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0004_alter_reserva_fech_entrada_alter_reserva_fech_salida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='hoteles',
        ),
    ]
