# Generated by Django 5.1.2 on 2024-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0005_rename_hotel_hoteles'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
