# Generated by Django 5.1.2 on 2024-11-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0005_rename_hotel_hoteles'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('Dni', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('mascotas', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='Estrellas',
            new_name='Estrella',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.IntegerField(choices=[(0, 'Doble'), (1, 'Triple'), (2, 'Cuadruple'), (3, 'Familar'), (4, 'Matrimonial'), (5, 'Pen house')]),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reserv_Hotel.cliente'),
            preserve_default=False,
        ),
    ]
