# Generated by Django 5.1.2 on 2024-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0006_habitacion_info_habitacion_ocupado'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField(max_length=8)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni',
            field=models.IntegerField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
