# Generated by Django 5.1.2 on 2024-11-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0006_cliente_rename_estrellas_servicio_estrella_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Estrella',
            field=models.IntegerField(max_length=5),
        ),
    ]
