# Generated by Django 5.1.2 on 2024-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0007_alter_servicio_estrella'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='Estrella',
        ),
    ]
