# Generated by Django 5.1.2 on 2024-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0007_cliente_reserva_dni_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
