# Generated by Django 5.1.2 on 2024-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0008_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
