# Generated by Django 5.1.2 on 2024-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0008_remove_servicio_estrella'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
