# Generated by Django 5.1.2 on 2024-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0010_alter_hoteles_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default=True, upload_to='productos'),
            preserve_default=False,
        ),
    ]
