# Generated by Django 5.1.2 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserv_Hotel', '0011_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Cliente',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
